# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2025-03-18 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=21)),
                ('public_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=21)),
                ('last_name', models.CharField(max_length=21)),
                ('username', models.CharField(max_length=21)),
                ('p1', models.CharField(max_length=21)),
                ('p2', models.CharField(max_length=21)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application1.reporter'),
        ),
    ]
