# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2025-03-19 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=21)),
                ('last_name', models.CharField(max_length=21)),
                ('username', models.CharField(max_length=21)),
                ('p1', models.CharField(max_length=21)),
                ('p2', models.CharField(max_length=21)),
                ('mobile_number', models.CharField(max_length=21)),
                ('email', models.CharField(max_length=21)),
            ],
        ),
    ]
