# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2025-03-18 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('cname', models.CharField(max_length=21)),
                ('address', models.CharField(max_length=21)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=21)),
                ('price', models.FloatField()),
                ('company', models.CharField(max_length=21)),
                ('m_date', models.DateField()),
                ('e_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='product',
            field=models.ManyToManyField(to='application1.products'),
        ),
    ]
